### ISSUE TITLE
random browser version doesn't match actual one

### ISSUE THREAD

**Issue by yuval1973** [iamdual/ua-generator#7] opened 2024-05-17 08:39 UTC
This is the code I'm using:

```
ua = ua_generator.generate(platform = 'windows', browser = 'chrome')
ua.headers.accept_ch('Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List')
driver.execute_cdp_cmd('Network.setExtraHTTPHeaders', {'headers': ua.headers.get()})
```

But this creates a problem and mismatch between the generated browser version and the actual one. This makes the package practically unusable.  You can see in the example that the generator made Chrome to be of version 95, but the actual version is 124. I'm not sure how to fix this. your generator should be aware of the real browser version and generate matching strings. Otherwise this creates a mismatch that can be easily detected. 

![image](https://github.com/iamdual/ua-generator/assets/163681651/5a5ca511-b927-4684-8e56-43694b23d942)

**Comment by iamdual** [comment] 2024-05-17 12:33
Hello, 

I don't know which client you are using, but I can say that this issue is not caused by the library. Based on my tests, the values generated by the `ClientHints` and `Headers` classes seem consistent. The ua-generator only produces strings and cannot affect the Client Hints values obtained from JavaScript environments (as mentioned in the image). 

Additionally, the "Sec-CH-UA-Full-Version" header is not generated by this library. It has been deprecated by the W3C and replaced with "Sec-CH-UA-Full-Version-List". You need to manually set the "Sec-CH-UA-Full-Version".

**Comment by yuval1973** [comment] 2024-05-17 18:42
I'm using Chrome and you can see that in the headers. The values that ua generates are consistent and this isn't my point.
My point is that applying everything to the headers and UA creates an inconsistent result bc Chrome reveals its real version when asked and through JS and the bottom line is an inconsistent results that defeats the purpose. If I do that I'm going to be blocked at once detected as a bot. The main question is - how to make sent fields consistent using the package? the example I sent was created by https://browserleaks.com/client-hints where I tested the sent results and revealed the mismatch. The question is how can we fix this?

**Comment by iamdual** [comment] 2024-05-17 22:36
> I'm using Chrome and you can see that in the headers. The values that ua generates are consistent and this isn't my point. My point is that applying everything to the headers and UA creates an inconsistent result bc Chrome reveals its real version when asked and through JS and the bottom line is an inconsistent results that defeats the purpose. If I do that I'm going to be blocked at once detected as a bot. The main question is - how to make sent fields consistent using the package? the example I sent was created by https://browserleaks.com/client-hints where I tested the sent results and revealed the mismatch. The question is how can we fix this?

Hello,

Starting from version 0.5.0, the functions that provide raw Client Hints values have been made public. Now, you can set the Client Hints values from clients like Selenium. However, you need to update the ua-generator first.

I tested it, and it worked.

```python
ua = ua_generator.generate(platform='windows', browser='chrome')
driver = webdriver.Chrome()
driver.execute_cdp_cmd('Network.setUserAgentOverride', {
    'userAgent': ua.text,
    'userAgentMetadata': {
        'brands': ua.ch.get_brands(),
        'fullVersionList': ua.ch.get_brands(full_version_list=True),
        'fullVersion': ua.ch.get_browser_version(),
        'platform': ua.ch.get_platform(),
        'platformVersion': ua.ch.get_platform_version(),
        'architecture': ua.ch.get_architecture(),
        'model': ua.ch.get_model(),
        'mobile': ua.ch.get_mobile(),
        'bitness': ua.ch.get_bitness(),
        'wow64': ua.ch.get_wow64(),
    }
})
```

**Comment by yuval1973** [comment] 2024-05-17 23:08
perfect! now everything is consistent

![image](https://github.com/iamdual/ua-generator/assets/163681651/e4d27fae-a835-4e81-9f6b-4755bb39f795)

**Comment by iamdual** [comment] 2024-05-18 00:20
I'm glad to hear that. Well, closing then.

**Closed by iamdual** 2024-05-18 00:20 UTC
Labels: enhancement

**Comment by yuval1973** [comment] 2024-05-18 06:29
I actually have one small request. 99% of Chrome versions vary today between 120-124, but you choose a random equally from 90-124 (see below).  So will you be able to either get rid of anything below 120 or even better, give a min-max range to choose from? this way you'll just generate a random between desired versions. This will also spare the need to update your package all the time since right now you have to choice about Chrome version changes if they release 125 and so on.

![image](https://github.com/iamdual/ua-generator/assets/163681651/9186426f-7936-42ac-a440-7e0232e181e9)

**Comment by iamdual** [comment] 2024-05-18 13:18
> I actually have one small request. 99% of Chrome versions vary today between 120-124, but you choose a random equally from 90-124 (see below). So will you be able to either get rid of anything below 120 or even better, give the caller a min-max range to choose from? this way you'll just generate a random between desired versions. This will also spare the need to update your package all the time since right now you have to choice about Chrome version changes if they release 125 and so on.

The main purpose of creating this library was actually to generate valid user-agent values. The versions were not of much importance. However, it would really be nice if the version customization could be implemented. There is already another request (#6) regarding the customization of versions, but I haven't had the time to address it.

**Comment by yuval1973** [comment] 2024-05-18 18:28
"_The main purpose of creating this library was actually to generate valid user-agent values_"

well "valid" doesn't mean that you simply pick random figures without considering reality. And if the reality is that 99% of Chrome versions are > 120, then you cannot by all means choose version 90 as probability equal to 124, but this is what happens today. I think that if you want a quick and dirty solution - but still better than today - simply release a version with only versions 120-124. 

As for other fields, I think over there is the same story. 95% of all Windows are > version 10, so you cannot pick version 6 or 6.1 equally as the others, but this is again what's happening today. Same thing with WOW64 which is almost nonexistent. So I do believe to turn the package from a toy to something which can be used in production code, these changes are necessary and in fact not difficult to make. For example you can easily add weights (=percentages) to all the versions you have and when you pick a random figure their weights are taken into account for example:

```
def getWeightedValueFrom(list):
      return random.choices([pair[0] for pair in list], weights = [pair[1] for pair in list], k = 1) 
```

**Comment by iamdual** [comment] 2024-05-18 19:52
Thank you for your suggestions. I will consider them next time.

**Comment by krishgalani** [comment] 2024-08-09 20:33
I understand the option to select a range of versions. But I don't get why you would want weighted values. Isn't the point of the random generator to uniformly generate all possible combinations of browser, device, platform? Maybe its because what I'm thinking is when you're webscraping you want to spread out your ua usages linearly as your number of queries increases, and not have a couple that are used in high frequency. @iamdual

**Comment by iamdual** [comment] 2024-08-09 20:37
> I understand the option to select a range of versions. But I don't get why you would want weighted values. Isn't the point of the random generator to uniformly generate all possible combinations of browser, device, platform, version? Maybe its because what I'm thinking is when you're webscraping you want to spread out your ua usages linearly as your number of queries increases, and not have a couple that are used in high frequency to avoid being blocked @iamdual

Yes, I agree, but it is also true that the usage rate of the latest versions is higher than the others. However, I would like to remind you that this feature is completely optional.
